name: Build OrangeFox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:arch

    env:
      DEVICE: lisa
      OEM: xiaomi
      DT_LINK: https://github.com/LineageOS/android_device_xiaomi_lisa.git -b lineage-21
      TARGET: bootimage
      OUTPUT: OrangeFox*.zip
      EXTRA_CMD: export OF_MAINTAINER=~jkoo
      OF_USE_LATEST_MAGISK: true
      SYNC_PATH: /tmp/work
      USE_CCACHE: 1
      CCACHE_SIZE: 50G
      CCACHE_DIR: /tmp/work/.ccache
      J_VAL: 16

    steps:
      - name: Checkout CI scripts
        uses: actions/checkout@v3

      - name: Sync OrangeFox sources
        env:
          DEVICE: ${{ env.DEVICE }}
          OEM: ${{ env.OEM }}
          DT_LINK: ${{ env.DT_LINK }}
          TARGET: ${{ env.TARGET }}
          OUTPUT: ${{ env.OUTPUT }}
          EXTRA_CMD: ${{ env.EXTRA_CMD }}
          OF_USE_LATEST_MAGISK: ${{ env.OF_USE_LATEST_MAGISK }}
          USE_CCACHE: ${{ env.USE_CCACHE }}
          CCACHE_SIZE: ${{ env.CCACHE_SIZE }}
          CCACHE_DIR: ${{ env.CCACHE_DIR }}
          J_VAL: ${{ env.J_VAL }}
        run: |
          bash -c "bash <(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh) --branch 14.1 --path ${{ env.SYNC_PATH }}/fox_14.1"

      - name: Build recovery
        env:
          DEVICE: ${{ env.DEVICE }}
          OEM: ${{ env.OEM }}
          DT_LINK: ${{ env.DT_LINK }}
          TARGET: ${{ env.TARGET }}
          OUTPUT: ${{ env.OUTPUT }}
          EXTRA_CMD: ${{ env.EXTRA_CMD }}
          OF_USE_LATEST_MAGISK: ${{ env.OF_USE_LATEST_MAGISK }}
          USE_CCACHE: ${{ env.USE_CCACHE }}
          CCACHE_SIZE: ${{ env.CCACHE_SIZE }}
          CCACHE_DIR: ${{ env.CCACHE_DIR }}
          J_VAL: ${{ env.J_VAL }}
        run: |
          cd ${{ env.SYNC_PATH }}/fox_14.1
          bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh)"

      - name: Upload recovery ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ofox-build
          path: ${{ env.SYNC_PATH }}/fox_14.1/out/target/product/${{ env.DEVICE }}/${{ env.OUTPUT }}
