name: Build OrangeFox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:arch

    env:
      FOX_BRANCH: fox_14.1
      DEVICE: lisa
      OEM: xiaomi
      DT_LINK: https://github.com/LineageOS/android_device_xiaomi_lisa.git -b lineage-21
      TARGET: bootimage
      OUTPUT: OrangeFox*.zip
      EXTRA_CMD: export OF_MAINTAINER=~jkoo
      OF_USE_LATEST_MAGISK: true
      SYNC_PATH: /tmp/work
      USE_CCACHE: 1
      CCACHE_SIZE: 50G
      CCACHE_DIR: /tmp/work/.ccache
      J_VAL: 16

    steps:
      - name: Checkout CI scripts (you can replace this with your repo if customized)
        uses: actions/checkout@v3

      - name: Sync OrangeFox sources
        run: bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh)"

      - name: Build recovery
        run: bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh)"

      - name: Upload recovery ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ofox-build
          path: ${{ env.SYNC_PATH }}/fox_${{ env.FOX_BRANCH }}/out/target/product/${{ env.DEVICE }}/${{ env.OUTPUT }}
